# Generated by Django 2.2.14 on 2020-08-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200801_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='imagech',
            new_name='image',
        ),
    ]
